---
title: October 31 vs. Nanaimo Clippers
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Team  
### Corsi: 58.27%  
### Fenwick: 58.14%  
### Overall Percent of expect Goals For: 65.97%  
### Overall Expected Goals For: 5.00  
### Overall Expected Goals Against: 2.58  
### Even Strength Percent of expect Goals For: 72.24%  
### Even Strength Expected Goals For: 4.65  
### Even Strength Expected Goals Against: 1.79  
## Game/Period Summary  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 4 & 0 & 1 & 5\\
\hline
On Net & 8 & 14 & 16 & 38\\
\hline
Missed & 3 & 3 & 4 & 10\\
\hline
Blocked & 5 & 7 & 13 & 25\\
\hline\hline
Total & 20 & 24 & 34 & 78  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 5 & 11 & 18 & 34\\
\hline
Missed & 1 & 4 & 2 & 7\\
\hline
Blocked & 5 & 5 & 9 & 19\\
\hline\hline
Total & 12 & 20 & 29 & 61  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 1 & 5 & 4 & 10\\
\hline
Missed & 1 & 0 & 0 & 1\\
\hline
Blocked & 0 & 2 & 5 & 7\\
\hline\hline
Total & 3 & 7 & 9 & 19  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 1 & 4 & 6 & 11\\
\hline
Missed & 0 & 2 & 1 & 3\\
\hline
Blocked & 0 & 2 & 2 & 4\\
\hline\hline
Total & 2 & 8 & 9 & 19  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 4 & 5 & 5 & 14\\
\hline
Missed & 0 & 2 & 2 & 4\\
\hline
Blocked & 2 & 2 & 6 & 10\\
\hline\hline
Total & 7 & 9 & 13 & 29  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 3 & 7 & 12\\
\hline
Missed & 1 & 1 & 0 & 2\\
\hline
Blocked & 2 & 0 & 3 & 5\\
\hline\hline
Total & 5 & 4 & 10 & 19  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 1 & 3\\
\hline
On Net & 3 & 4 & 7 & 14\\
\hline
Missed & 2 & 1 & 2 & 5\\
\hline
Blocked & 3 & 3 & 2 & 8\\
\hline\hline
Total & 10 & 8 & 12 & 30  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 4 & 5 & 11\\
\hline
Missed & 0 & 1 & 1 & 2\\
\hline
Blocked & 3 & 3 & 4 & 10\\
\hline\hline
Total & 5 & 8 & 10 & 23  
\end{tabular}
  
## Even Strength  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 3 & 0 & 1 & 4\\
\hline
On Net & 8 & 12 & 16 & 36\\
\hline
Missed & 3 & 3 & 4 & 10\\
\hline
Blocked & 5 & 6 & 13 & 24\\
\hline\hline
Total & 19 & 21 & 34 & 74  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 4 & 9 & 18 & 31\\
\hline
Missed & 0 & 3 & 2 & 5\\
\hline
Blocked & 4 & 4 & 9 & 17\\
\hline\hline
Total & 8 & 16 & 29 & 53  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 1 & 3 & 4 & 8\\
\hline
Missed & 1 & 0 & 0 & 1\\
\hline
Blocked & 0 & 1 & 5 & 6\\
\hline\hline
Total & 3 & 4 & 9 & 16  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 2 & 6 & 9\\
\hline
Missed & 0 & 1 & 1 & 2\\
\hline
Blocked & 0 & 1 & 2 & 3\\
\hline\hline
Total & 1 & 4 & 9 & 14  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 4 & 5 & 5 & 14\\
\hline
Missed & 0 & 2 & 2 & 4\\
\hline
Blocked & 2 & 2 & 6 & 10\\
\hline\hline
Total & 7 & 9 & 13 & 29  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 3 & 7 & 11\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 1 & 0 & 3 & 4\\
\hline\hline
Total & 2 & 4 & 10 & 16  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 1 & 2\\
\hline
On Net & 3 & 4 & 7 & 14\\
\hline
Missed & 2 & 1 & 2 & 5\\
\hline
Blocked & 3 & 3 & 2 & 8\\
\hline\hline
Total & 9 & 8 & 12 & 29  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 4 & 5 & 11\\
\hline
Missed & 0 & 1 & 1 & 2\\
\hline
Blocked & 3 & 3 & 4 & 10\\
\hline\hline
Total & 5 & 8 & 10 & 23  
\end{tabular}
  
## Powerplay  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 0 & 2 & 0 & 2\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 1 & 3 & 0 & 4  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 2 & 0 & 2\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 0 & 3 & 0 & 3  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 1 & 0 & 0 & 1  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
## Penalty Kill  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 1 & 2 & 0 & 3\\
\hline
Missed & 1 & 1 & 0 & 2\\
\hline
Blocked & 1 & 1 & 0 & 2\\
\hline\hline
Total & 4 & 4 & 0 & 8  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 0 & 2 & 0 & 2\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 1 & 4 & 0 & 5  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 0 & 0 & 1\\
\hline
Missed & 1 & 0 & 0 & 1\\
\hline
Blocked & 1 & 0 & 0 & 1\\
\hline\hline
Total & 3 & 0 & 0 & 3  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
\pagebreak
