---
title: November 7th vs. Alberni Bulldogs
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Team  
### Corsi: 47.06%  
### Fenwick: 43.96%  
### Overall Percent of expect Goals For: 60.67%  
### Overall Expected Goals For: 6.45  
### Overall Expected Goals Against: 4.18  
### Even Strength Percent of expect Goals For: 61.64%  
### Even Strength Expected Goals For: 5.82  
### Even Strength Expected Goals Against: 3.62  
## Game/Period Summary  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 3 & 0 & 0 & 3\\
\hline
On Net & 11 & 6 & 9 & 26\\
\hline
Missed & 7 & 3 & 6 & 16\\
\hline
Blocked & 2 & 6 & 9 & 17\\
\hline\hline
Total & 23 & 15 & 24 & 62  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 1 & 3\\
\hline
On Net & 11 & 12 & 15 & 38\\
\hline
Missed & 1 & 8 & 7 & 16\\
\hline
Blocked & 1 & 7 & 7 & 15\\
\hline\hline
Total & 15 & 27 & 30 & 72  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 0 & 2\\
\hline
On Net & 3 & 0 & 4 & 7\\
\hline
Missed & 3 & 1 & 0 & 4\\
\hline
Blocked & 0 & 0 & 5 & 5\\
\hline\hline
Total & 8 & 1 & 9 & 18  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 4 & 4 & 8 & 16\\
\hline
Missed & 1 & 2 & 4 & 7\\
\hline
Blocked & 1 & 2 & 2 & 5\\
\hline\hline
Total & 6 & 8 & 14 & 28  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 3 & 3 & 1 & 7\\
\hline
Missed & 2 & 1 & 2 & 5\\
\hline
Blocked & 1 & 1 & 2 & 4\\
\hline\hline
Total & 6 & 5 & 5 & 16  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 3 & 3 & 8\\
\hline
Missed & 0 & 3 & 2 & 5\\
\hline
Blocked & 0 & 1 & 4 & 5\\
\hline\hline
Total & 2 & 7 & 9 & 18  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 3 & 2 & 4 & 9\\
\hline
Missed & 2 & 1 & 4 & 7\\
\hline
Blocked & 1 & 2 & 2 & 5\\
\hline\hline
Total & 7 & 5 & 10 & 22  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 1 & 3\\
\hline
On Net & 3 & 3 & 4 & 10\\
\hline
Missed & 0 & 3 & 1 & 4\\
\hline
Blocked & 0 & 3 & 1 & 4\\
\hline\hline
Total & 5 & 9 & 7 & 21  
\end{tabular}
  
### Period: 4  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 1 & 0 & 3\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 3 & 0 & 3\\
\hline\hline
Total & 2 & 4 & 0 & 6  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 2 & 0 & 4\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 2 & 3 & 0 & 5  
\end{tabular}
  
## Even Strength  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 0 & 2\\
\hline
On Net & 10 & 5 & 8 & 23\\
\hline
Missed & 7 & 3 & 5 & 15\\
\hline
Blocked & 1 & 6 & 9 & 16\\
\hline\hline
Total & 20 & 14 & 22 & 56  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 1 & 3\\
\hline
On Net & 9 & 9 & 15 & 33\\
\hline
Missed & 1 & 7 & 7 & 15\\
\hline
Blocked & 1 & 6 & 5 & 12\\
\hline\hline
Total & 13 & 22 & 28 & 63  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 0 & 2\\
\hline
On Net & 3 & 0 & 4 & 7\\
\hline
Missed & 3 & 1 & 0 & 4\\
\hline
Blocked & 0 & 0 & 5 & 5\\
\hline\hline
Total & 8 & 1 & 9 & 18  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 4 & 4 & 8 & 16\\
\hline
Missed & 1 & 2 & 4 & 7\\
\hline
Blocked & 1 & 2 & 2 & 5\\
\hline\hline
Total & 6 & 8 & 14 & 28  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 3 & 1 & 6\\
\hline
Missed & 2 & 1 & 2 & 5\\
\hline
Blocked & 1 & 1 & 2 & 4\\
\hline\hline
Total & 5 & 5 & 5 & 15  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 2 & 3 & 7\\
\hline
Missed & 0 & 3 & 2 & 5\\
\hline
Blocked & 0 & 1 & 2 & 3\\
\hline\hline
Total & 2 & 6 & 7 & 15  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 3 & 1 & 3 & 7\\
\hline
Missed & 2 & 1 & 3 & 6\\
\hline
Blocked & 0 & 2 & 2 & 4\\
\hline\hline
Total & 5 & 4 & 8 & 17  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 1 & 3\\
\hline
On Net & 1 & 1 & 4 & 6\\
\hline
Missed & 0 & 2 & 1 & 3\\
\hline
Blocked & 0 & 2 & 1 & 3\\
\hline\hline
Total & 3 & 5 & 7 & 15  
\end{tabular}
  
### Period: 4  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 1 & 0 & 3\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 3 & 0 & 3\\
\hline\hline
Total & 2 & 4 & 0 & 6  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 2 & 0 & 4\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 2 & 3 & 0 & 5  
\end{tabular}
  
## Powerplay  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 1 & 1 & 1 & 3\\
\hline
Missed & 0 & 0 & 1 & 1\\
\hline
Blocked & 1 & 0 & 0 & 1\\
\hline\hline
Total & 3 & 1 & 2 & 6  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 0 & 0 & 1\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 1 & 0 & 0 & 1  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 0 & 1 & 1 & 2\\
\hline
Missed & 0 & 0 & 1 & 1\\
\hline
Blocked & 1 & 0 & 0 & 1\\
\hline\hline
Total & 2 & 1 & 2 & 5  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 4  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
## Penalty Kill  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 3 & 0 & 5\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 1 & 2 & 3\\
\hline\hline
Total & 2 & 5 & 2 & 9  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 1 & 0 & 1\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 2 & 2\\
\hline\hline
Total & 0 & 1 & 2 & 3  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 2 & 0 & 4\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 2 & 4 & 0 & 6  
\end{tabular}
  
### Period: 4  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
\pagebreak
