---
title: November 7th vs. Alberni Bulldogs
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 91: Veilleux  
### Corsi: 44.44%  
### Fenwick: 42.42%  
### Even Strength Percent of expect Goals For: 64.45%  
### Even Strength Expected Goals For: 1.88  
### Even Strength Expected Goals Against: 1.04  
## Even Strength  
***
### Game Total:  
##### number of shifts: 43  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 2 & 4 & 8\\
\hline
Missed & 4 & 1 & 1 & 6\\
\hline
Blocked & 1 & 1 & 4 & 6\\
\hline\hline
Total & 7 & 4 & 9 & 20\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 3 & 3 & 7 & 13\\
\hline
Missed & 0 & 3 & 3 & 6\\
\hline
Blocked & 1 & 3 & 2 & 6\\
\hline\hline
Total & 4 & 9 & 12 & 25\\
\end{tabular}
  
### Period: 1  
##### number of shifts: 16  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 0 & 2 & 3\\
\hline
Missed & 1 & 1 & 0 & 2\\
\hline
Blocked & 0 & 0 & 3 & 3\\
\hline\hline
Total & 2 & 1 & 5 & 8\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 1 & 5 & 7\\
\hline
Missed & 0 & 1 & 2 & 3\\
\hline
Blocked & 1 & 1 & 2 & 4\\
\hline\hline
Total & 2 & 3 & 9 & 14\\
\end{tabular}
  
### Period: 2  
##### number of shifts: 17  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 1 & 1 & 3\\
\hline
Missed & 2 & 0 & 1 & 3\\
\hline
Blocked & 1 & 1 & 0 & 2\\
\hline\hline
Total & 4 & 2 & 2 & 8\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 2 & 1 & 5\\
\hline
Missed & 0 & 2 & 0 & 2\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 2 & 5 & 1 & 8\\
\end{tabular}
  
### Period: 3  
##### number of shifts: 10  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 1 & 1 & 2\\
\hline
Missed & 1 & 0 & 0 & 1\\
\hline
Blocked & 0 & 0 & 1 & 1\\
\hline\hline
Total & 1 & 1 & 2 & 4\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 1 & 1\\
\hline
Missed & 0 & 0 & 1 & 1\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 0 & 1 & 2 & 3\\
\end{tabular}
  
### Period: 4  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
## Powerplay  
***
### Game Total:  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
### Period: 1  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
### Period: 2  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
### Period: 3  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
### Period: 4  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
## Penalty Kill  
***
### Game Total:  
##### number of shifts: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 2 & 2\\
\hline\hline
Total & 0 & 0 & 2 & 2\\
\end{tabular}
  
### Period: 1  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
### Period: 2  
##### number of shifts: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 2 & 2\\
\hline\hline
Total & 0 & 0 & 2 & 2\\
\end{tabular}
  
### Period: 3  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
### Period: 4  
##### number of shifts: 0  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0\\
\end{tabular}
  
### Fenwick: 42.42%  
\pagebreak
