---
title: sept 26 vs. Nanaimo Clippers
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Team  
## Game/Period Summary  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 3 & 0 & 0 & 3\\
\hline
On Net & 12 & 10 & 17 & 39\\
\hline
Missed & 3 & 6 & 7 & 16\\
\hline
Blocked & 1 & 8 & 7 & 16\\
\hline\hline
Total & 19 & 24 & 31 & 74  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 3 & 0 & 1 & 4\\
\hline
On Net & 7 & 7 & 17 & 31\\
\hline
Missed & 1 & 3 & 5 & 9\\
\hline
Blocked & 1 & 1 & 5 & 7\\
\hline\hline
Total & 12 & 11 & 28 & 51  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 2 & 1 & 4\\
\hline
Missed & 0 & 2 & 4 & 6\\
\hline
Blocked & 0 & 4 & 2 & 6\\
\hline\hline
Total & 1 & 8 & 7 & 16  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 0 & 2\\
\hline
On Net & 4 & 4 & 4 & 12\\
\hline
Missed & 1 & 2 & 2 & 5\\
\hline
Blocked & 0 & 0 & 2 & 2\\
\hline\hline
Total & 7 & 6 & 8 & 21  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 5 & 4 & 8 & 17\\
\hline
Missed & 1 & 2 & 1 & 4\\
\hline
Blocked & 0 & 1 & 2 & 3\\
\hline\hline
Total & 7 & 7 & 11 & 25  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 1 & 2\\
\hline
On Net & 3 & 1 & 9 & 13\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 4 & 2 & 10 & 16  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 0 & 2\\
\hline
On Net & 6 & 4 & 8 & 18\\
\hline
Missed & 2 & 2 & 2 & 6\\
\hline
Blocked & 1 & 3 & 3 & 7\\
\hline\hline
Total & 11 & 9 & 13 & 33  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 2 & 4 & 6\\
\hline
Missed & 0 & 0 & 3 & 3\\
\hline
Blocked & 1 & 1 & 3 & 5\\
\hline\hline
Total & 1 & 3 & 10 & 14  
\end{tabular}
  
## Even Strength  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 0 & 2\\
\hline
On Net & 9 & 9 & 13 & 31\\
\hline
Missed & 3 & 4 & 7 & 14\\
\hline
Blocked & 1 & 5 & 7 & 13\\
\hline\hline
Total & 15 & 18 & 27 & 60  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 3 & 0 & 0 & 3\\
\hline
On Net & 7 & 7 & 14 & 28\\
\hline
Missed & 1 & 2 & 5 & 8\\
\hline
Blocked & 1 & 1 & 5 & 7\\
\hline\hline
Total & 12 & 10 & 24 & 46  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 1 & 2 & 0 & 3\\
\hline
Missed & 0 & 1 & 4 & 5\\
\hline
Blocked & 0 & 2 & 2 & 4\\
\hline\hline
Total & 1 & 5 & 6 & 12  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 0 & 0 & 2\\
\hline
On Net & 4 & 4 & 4 & 12\\
\hline
Missed & 1 & 1 & 2 & 4\\
\hline
Blocked & 0 & 0 & 2 & 2\\
\hline\hline
Total & 7 & 5 & 8 & 20  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 2 & 4 & 7 & 13\\
\hline
Missed & 1 & 2 & 1 & 4\\
\hline
Blocked & 0 & 1 & 2 & 3\\
\hline\hline
Total & 4 & 7 & 10 & 21  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 3 & 1 & 6 & 10\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 4 & 2 & 6 & 12  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 6 & 3 & 6 & 15\\
\hline
Missed & 2 & 1 & 2 & 5\\
\hline
Blocked & 1 & 2 & 3 & 6\\
\hline\hline
Total & 10 & 6 & 11 & 27  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 2 & 4 & 6\\
\hline
Missed & 0 & 0 & 3 & 3\\
\hline
Blocked & 1 & 1 & 3 & 5\\
\hline\hline
Total & 1 & 3 & 10 & 14  
\end{tabular}
  
## Powerplay  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 3 & 1 & 2 & 6\\
\hline
Missed & 0 & 2 & 0 & 2\\
\hline
Blocked & 0 & 3 & 0 & 3\\
\hline\hline
Total & 4 & 6 & 2 & 12  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 1 & 1\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 1 & 1 & 2  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 1 & 1\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 2 & 0 & 2\\
\hline\hline
Total & 0 & 3 & 1 & 4  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 1 & 0 & 1  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 3 & 0 & 1 & 4\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 3 & 0 & 1 & 4  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 1 & 1\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 1 & 1  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 1 & 0 & 0 & 1\\
\hline
On Net & 0 & 1 & 0 & 1\\
\hline
Missed & 0 & 1 & 0 & 1\\
\hline
Blocked & 0 & 1 & 0 & 1\\
\hline\hline
Total & 1 & 3 & 0 & 4  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
## Penalty Kill  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 2 & 2\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 2 & 2  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 1 & 1\\
\hline
On Net & 0 & 0 & 2 & 2\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 3 & 3  
\end{tabular}
  
### Period: 1  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Period: 2  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 1 & 1\\
\hline
On Net & 0 & 0 & 2 & 2\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 3 & 3  
\end{tabular}
  
### Period: 3  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 2 & 2\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 2 & 2  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
### Corsi: 56.60%  
### Fenwick: 54.65%  
\pagebreak
