---
title: November 17th vs. Nanaimo Clippers
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Team  
### Corsi: 47.00%  
### Fenwick: 48.15%  
### Overall Percent of expect Goals For: 54.20%  
### Overall Expected Goals For: 4.82  
### Overall Expected Goals Against: 4.07  
### Even Strength Percent of expect Goals For: 49.06%  
### Even Strength Expected Goals For: 3.79  
### Even Strength Expected Goals Against: 3.93  
## Game/Period Summary  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 1 & 1 & 4\\
\hline
On Net & 9 & 6 & 17 & 32\\
\hline
Missed & 4 & 7 & 2 & 13\\
\hline
Blocked & 1 & 4 & 7 & 12\\
\hline\hline
Total & 16 & 18 & 27 & 61  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 5 & 0 & 0 & 5\\
\hline
On Net & 6 & 8 & 18 & 32\\
\hline
Missed & 3 & 3 & 4 & 10\\
\hline
Blocked & 2 & 4 & 7 & 13\\
\hline\hline
Total & 16 & 15 & 29 & 60  
\end{tabular}
  
## Even Strength  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 2 & 1 & 1 & 4\\
\hline
On Net & 7 & 4 & 15 & 26\\
\hline
Missed & 3 & 4 & 2 & 9\\
\hline
Blocked & 0 & 3 & 5 & 8\\
\hline\hline
Total & 12 & 12 & 23 & 47  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 5 & 0 & 0 & 5\\
\hline
On Net & 6 & 8 & 15 & 29\\
\hline
Missed & 3 & 1 & 4 & 8\\
\hline
Blocked & 2 & 3 & 6 & 11\\
\hline\hline
Total & 16 & 12 & 25 & 53  
\end{tabular}
  
## Powerplay  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 2 & 2 & 1 & 5\\
\hline
Missed & 1 & 3 & 0 & 4\\
\hline
Blocked & 0 & 1 & 2 & 3\\
\hline\hline
Total & 3 & 6 & 3 & 12  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 0 & 0\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 0 & 0 & 0 & 0\\
\hline\hline
Total & 0 & 0 & 0 & 0  
\end{tabular}
  
## Penalty Kill  
***
### Game Total:  
#### FOR  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 1 & 1\\
\hline
Missed & 0 & 0 & 0 & 0\\
\hline
Blocked & 1 & 0 & 0 & 1\\
\hline\hline
Total & 1 & 0 & 1 & 2  
\end{tabular}
\vspace{5mm}  
#### AGAINST  
  
\begin{tabular}{ c || c | c | c || c}
& High & Medium & Low & Total\\  
\hline\hline
Goal & 0 & 0 & 0 & 0\\
\hline
On Net & 0 & 0 & 3 & 3\\
\hline
Missed & 0 & 2 & 0 & 2\\
\hline
Blocked & 0 & 1 & 1 & 2\\
\hline\hline
Total & 0 & 3 & 4 & 7  
\end{tabular}
  
\pagebreak
